team1_ecommerce/shop/urls.py
from django.conf.urls import url

import views

urlpatterns = [
    url(r'^list/$', views.GoodsListView.as_view(), name='shop_list'),
    url(r'^$', views.shop_index, name='shop_index'),
    url(r'^list/most_rated/$', views.GoodsListView.as_view(ordering='-rating__average_rating'),
        name='shop_list_most_rated'),
    url(r'^list/lastest/$', views.GoodsListView.as_view(ordering='-receipt_date'),
        name='shop_list_lastest'),
    url(r'^add_review/$', views.GoodsReviewAddUpdate.as_view(), name='shop_review'),
    url(r'^del_review/$', views.ReviewDeleteView.as_view(), name='shop_review_delete'),
    url(r'^detail/(?P<slug>[-\w]+)/$', views.GoodsDetailView.as_view(), name='shop_detail'),
    url(r'^tag/(?P<slug>[-\w]+)/$', views.TagsListView.as_view(), name='shop_tag'),
    url(r'^category/(?P<slug>[-\w]+)/$', views.CategoryListView.as_view(), name='shop_category'),
    url(r'^brand/(?P<slug>[-\w]+)/$', views.ManufacturerListView.as_view(), name='shop_manufacturer'),
]

team1_ecommerce/team1_ecommerce/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from shop import urls as shop_urls
from shop import views
from users import urls as users_urls
from orders import urls as orders_urls
from team1_ecommerce import settings

urlpatterns = [
                  url(r'^$', views.shop_index, name='index'),
                  url(r'^grappelli/', include('grappelli.urls')),
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^shop/', include(shop_urls)),
                  url(r'^users/', include(users_urls)),
                  url(r'^orders/', include(orders_urls)),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team1_ecommerce/shop/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.core.urlresolvers import reverse

from utils import unique_slugify


class Category(models.Model):
    """
    Class category
    """

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if len(self.slug) == 0:
            unique_slugify(self, self.name)

        super(Category, self).save(force_insert=force_insert, force_update=force_update, using=using,
                                   update_fields=update_fields)

    def get_absolute_url(self):
        return reverse('shop_category', kwargs={'slug': self.slug})

    def __unicode__(self):
        return self.name


class Tag(models.Model):
    tag = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if len(self.slug) == 0:
            unique_slugify(self, self.tag)

        super(Tag, self).save(force_insert=force_insert, force_update=force_update, using=using,
                              update_fields=update_fields)

    def get_absolute_url(self):
        return reverse('shop_tag', kwargs={'slug': self.slug})

    def __unicode__(self):
        return self.tag


class Rating(models.Model):
    CHOICES_RATING = (
        ('0', 'No rated'),
        ('1', 'Poor'),
        ('2', 'Fair'),
        ('3', 'Average'),
        ('4', 'Good'),
        ('5', 'Excellent'),
    )

    rating = models.CharField(max_length=1, choices=CHOICES_RATING, default='0')
    average_rating = models.FloatField(default=0)
    sum_rating = models.IntegerField(default=0)
    rating_counter = models.IntegerField(default=0)
    name = models.CharField(max_length=50)

    def count_rating(self):
        reviews = self.goods.review_set.all()
        self.average_rating = 0
        self.rating_counter = 0
        self.sum_rating = 0
        for review in reviews:
            if review.rating:
                self.rating_counter += 1
            self.sum_rating += review.rating
        if self.sum_rating and self.rating_counter:
            self.average_rating = float(self.sum_rating) / self.rating_counter

    def __unicode__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=50, unique=True)
    logo = models.ImageField(blank=True)
    description = models.CharField(max_length=50, blank=True)
    slug = models.SlugField(blank=True, unique=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if len(self.slug) == 0:
            unique_slugify(self, self.name)

        super(Manufacturer, self).save(force_insert=force_insert, force_update=force_update, using=using,
                                       update_fields=update_fields)

    def get_absolute_url(self):
        return reverse('shop_manufacturer', kwargs={'slug': self.slug})

    def __unicode__(self):
        return self.name


class Goods(models.Model):
    class Meta:
        verbose_name_plural = 'Goods'

    category = models.ForeignKey(Category)
    manufacturer = models.ForeignKey(Manufacturer)
    rating = models.OneToOneField(Rating, null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.FloatField(default=0)
    old_price = models.FloatField(default=0)
    in_stock = models.BooleanField(default=True)
    discount = models.FloatField(default=0)
    slug = models.SlugField(unique=True, blank=True)
    receipt_date = models.DateField(auto_now=True)

    def delete(self, using=None):
        if self.rating:
            self.rating.delete()
        super(Goods, self).delete(using=using)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.rating:
            self.rating = Rating.objects.create(name=self.name)

        if len(self.slug) == 0:
            unique_slugify(self, self.name)

        if self.old_price > self.price > 0 and self.discount == 0:
            self.discount = round((self.old_price - self.price) / self.old_price * 100)
        elif self.old_price == 0 and self.price > 0 and 100 > self.discount > 0:
            self.old_price = self.price
            self.price -= round(self.price * self.discount / 100)

        super(Goods, self).save(force_insert=force_insert, force_update=force_update, using=using,
                                update_fields=update_fields)

    def get_absolute_url(self):
        return reverse('shop_detail', kwargs={'slug': self.slug})

    def __unicode__(self):
        return self.name


class Image(models.Model):
    goods = models.ForeignKey(Goods)
    image = models.ImageField(blank=True)
    description = models.CharField(max_length=50, blank=True)


class Review(models.Model):
    from users.models import UserProfile
    goods = models.ForeignKey(Goods)
    author = models.ForeignKey(UserProfile)
    review_text = models.TextField(max_length=10000, blank=True)
    published = models.DateTimeField(auto_now=True)
    rating = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(Review, self).save(force_insert=force_insert, force_update=force_update, using=using,
                                 update_fields=update_fields)
        self.goods.rating.count_rating()
        self.goods.rating.save()

    def delete(self, using=None):
        super(Review, self).delete(using=using)
        self.goods.rating.count_rating()
        self.goods.rating.save()

    def __unicode__(self):
        return self.author.username + '-' + self.goods.name

team1_ecommerce/shop/forms.py
from django import forms

from .models import Goods


class GoodsForm(forms.ModelForm):
    class Meta:
        model = Goods
        fields = ['name', 'description', 'rating', 'tags', 'price', 'in_stock', 'discount', 'slug']

team1_ecommerce/shop/views.py
from braces.views import LoginRequiredMixin, AjaxResponseMixin, JSONResponseMixin, SuperuserRequiredMixin
from django.contrib import messages
from django.db import transaction
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Goods, Review, Tag, Manufacturer, Category

ORDERING = {
    'new': '-receipt_date',
    'old': 'receipt_date',
    'has_discount': '-discount',
    'price_asc': 'price',
    'price_desc': '-price',
    'rating': '-rating__average_rating'
}

LIST_VIEW = [
    'normal',
    'string'
]


class GoodsReviewAddUpdate(LoginRequiredMixin, View):
    @transaction.non_atomic_requests
    def post(self, request, *args, **kwargs):
        goods_id = request.POST.get('goods_id', None)
        review_rating = request.POST.get('rating', '0')
        review_text = request.POST.get('review_text', '')
        delete = request.POST.get('delete', None)
        user = request.user
        goods = get_object_or_404(Goods, pk=goods_id)
        if delete:
            try:
                Review.objects.get(goods=goods, author=user).delete()
                messages.success(request, 'Your review was deleted!')
            except Review.DoesNotExist:
                messages.error(request, 'Review not found!')
            return redirect(request.META['HTTP_REFERER'])

        with transaction.atomic():
            review, created = Review.objects.get_or_create(goods=goods, author=user)
            review.rating = review_rating
            review.review_text = review_text
            review.save()
            if created:
                messages.success(request, 'Your review was submitted! Thank you!')
            else:
                messages.success(request, 'Your review was updated! Thank you!')
            return redirect(request.META['HTTP_REFERER'])


class GoodsListView(ListView):
    paginate_by = 6
    model = Goods
    ordering = '-in_stock'

    def post(self, request, **kwargs):
        if request.GET.get('set_sort_order') in ORDERING:
            request.session['sort_order'] = request.GET.get('set_sort_order')
        if request.POST.get('set_list_view') in LIST_VIEW:
            if request.POST.get('set_list_view') == 'normal':
                request.session['per_page'] = '6'
            else:
                request.session['per_page'] = '12'
            request.session['list_view'] = request.POST.get('set_list_view')

        if request.GET.get('set_per_page'):
            if request.GET.get('set_per_page').isdigit():
                if int(request.GET.get('set_per_page')) <= 100:
                    request.session['per_page'] = request.GET.get('set_per_page')

        return redirect(request.META['HTTP_REFERER'])

    def get_ordering(self):
        return ['-in_stock', ORDERING[self.request.session.get('sort_order')]]

    def get_paginate_by(self, queryset):
        return self.request.session.get('per_page', self.paginate_by)

    def get_context_data(self, **kwargs):
        context = super(GoodsListView, self).get_context_data()
        category = self.request.GET.getlist('category', None)
        tag = self.request.GET.getlist('tag', None)
        brand = self.request.GET.getlist('brand', None)
        if category:
            context['current_category'] = Category.objects.filter(slug__in=category)
        if tag:
            context['current_tag'] = Tag.objects.filter(slug__in=tag)
        if brand:
            context['current_brand'] = Manufacturer.objects.filter(slug__in=brand)
        return context

    def get_queryset(self):
        query = super(GoodsListView, self).get_queryset()
        sequence = {}
        category = self.request.GET.getlist('category', None)
        tags = self.request.GET.getlist('tag', None)
        brand = self.request.GET.getlist('brand', None)
        if category:
            sequence['category__slug__in'] = category
        if brand:
            sequence['manufacturer__slug__in'] = brand
        if sequence:
            query = query.filter(**sequence).distinct()
        for tag in tags:
            query = query.filter(tags__slug=tag)
        return query


class GoodsDetailView(DetailView):
    model = Goods

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(GoodsDetailView, self).get_context_data(**kwargs)
        context['is_goods_rated_by_user'] = False
        if user.is_authenticated():
            goods = context['goods']
            try:
                review = goods.review_set.get(author=user)
                context['review_text'] = review.review_text
                context['rating'] = review.rating
                context['is_goods_rated_by_user'] = True
            except Review.DoesNotExist:
                context['review_text'] = ''
                context['rating'] = 0
        return context


def shop_index(request):
    latest = Goods.objects.all().order_by('-receipt_date')[:5]
    most_popular = Goods.objects.all().order_by('-rating__average_rating')[:5]
    return render(request, 'shop/index.html', {'latest': latest, 'most_popular': most_popular})


class TagsListView(GoodsListView):
    def get_queryset(self):
        slug = self.kwargs['slug']
        return super(TagsListView, self).get_queryset().filter(tags__slug=slug)

    def get_context_data(self, **kwargs):
        query_id = self.get_queryset().values_list('id').distinct()
        query = Goods.objects.filter(id__in=query_id)
        context = super(TagsListView, self).get_context_data(**kwargs)
        context['current_tag'] = Tag.objects.filter(slug=self.kwargs['slug'])
        context['categories'] = self.get_queryset().values_list('category__name', 'category__slug').order_by(
            'category__name').distinct()
        manufacturers_id = query.values_list('manufacturer', flat=True).order_by(
            'manufacturer__name').distinct()
        manufacturer_query = Manufacturer.objects.filter(id__in=manufacturers_id)
        manufacturers = []
        for manufacturer in manufacturer_query:
            manufacturers.append((manufacturer, query.filter(manufacturer=manufacturer).count()))
        context['manufacturers'] = manufacturers
        return context


class CategoryListView(GoodsListView):
    def get_queryset(self):
        slug = self.kwargs['slug']
        return super(CategoryListView, self).get_queryset().filter(category__slug=slug)

    def get_context_data(self, **kwargs):
        query_id = self.get_queryset().values_list('id').distinct()
        query = Goods.objects.filter(id__in=query_id)
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = Category.objects.filter(slug=self.kwargs['slug'])
        manufacturers_id = query.values_list('manufacturer', flat=True).distinct()
        manufacturer_query = Manufacturer.objects.filter(id__in=manufacturers_id)
        manufacturers = []
        for manufacturer in manufacturer_query:
            manufacturers.append((manufacturer, query.filter(manufacturer=manufacturer).count()))
        context['manufacturers'] = manufacturers
        tags_id = query.values_list('tags', flat=True)
        tags_query = Tag.objects.filter(id__in=tags_id)
        tags = []
        for tag in tags_query:
            tags.append((tag, query.filter(tags=tag).count()))
        context['tags'] = tags
        return context


class ManufacturerListView(GoodsListView):
    def get_queryset(self):
        slug = self.kwargs['slug']
        return super(ManufacturerListView, self).get_queryset().filter(manufacturer__slug=slug)

    def get_context_data(self, **kwargs):
        query_id = self.get_queryset().values_list('id').distinct()
        query = Goods.objects.filter(id__in=query_id)
        context = super(ManufacturerListView, self).get_context_data(**kwargs)
        context['current_brand'] = Manufacturer.objects.filter(slug=self.kwargs['slug'])
        context['categories'] = query.values_list('category__name', 'category__slug').order_by(
            'category__name').distinct()
        tags_id = query.values_list('tags', flat=True)
        tags_query = Tag.objects.filter(id__in=tags_id)
        tags = []
        for tag in tags_query:
            tags.append((tag, query.filter(tags=tag).count()))
        context['tags'] = tags
        return context


class ReviewDeleteView(LoginRequiredMixin, SuperuserRequiredMixin, JSONResponseMixin, AjaxResponseMixin, View):
    def post(self, request, *args, **kwargs):
        review_id = request.POST.get('review_id', None)
        try:
            Review.objects.get(id=review_id).delete()
            data = {'status': 'ok', 'message': ['Review deleted']}
            return self.render_json_response(data)
        except Review.DoesNotExist:
            data = {'status': 'fail', 'message': ['Review not found!']}
            return self.render_json_response(data)

team1_ecommerce/templates/shop/goods_detail.html
{% extends 'base.html' %}
{% load static %}
{% load rating %}
{% load thumbnail %}
{% block body %}
    <div class="row">
        <div class="col-md-3 col-lg-2">
            {% include 'shop/shop_navigation.html' %}
        </div>
        <div class="col-md-9 col-lg-10">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>{{ goods.name }}</h4>
                </div>
                <div class="panel-body">
                    <div>
                        <div id="carousel-pictures" class="carousel slide hidden-xs" data-ride="carousel">
                            <!-- Indicators -->

                            <ol class="carousel-indicators">
                                {% for image in goods.image_set.all %}
                                    <li data-target="#carousel-pictures" data-slide-to="{{ forloop.counter0 }}"
                                        {% if forloop.first %}class="active">{% endif %}</li>
                                {% endfor %}
                            </ol>

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner" role="listbox">
                                {% for image in goods.image_set.all %}
                                    <div class="item {% if forloop.first %}active{% endif %}">
                                        {% thumbnail image.image "400x300" padding=True as im %}
                                            <img src="{{ im.url }}" class="center-block">
                                            <div class="carousel-caption">
                                                {{ image.description }}
                                            </div>
                                            </div>
                                        {% endthumbnail %}
                                {% endfor %}

                                <!-- Controls -->
                                <a class="left carousel-control" href="#carousel-pictures" role="button"
                                   data-slide="prev">
                                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="right carousel-control" href="#carousel-pictures" role="button"
                                   data-slide="next">
                                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="pull-left" style="margin-right: 10px">
                            {% thumbnail goods.manufacturer.logo "160x120" as im %}
                                <img src="{{ im.url }}">
                            {% endthumbnail %}

                        </div>
                        <div>
                            {% lorem %}
                        </div>
                        <table class="table table-condensed table-striped">
                            <tr>
                                <td>Description</td>
                                <td>{{ goods.description }}</td>
                            </tr>
                            <tr>
                                <td>Price</td>
                                <td>{{ goods.price }}</td>
                            </tr>
                            <tr>
                                <td>Category</td>
                                <td>
                                    <a href="{{ goods.category.get_absolute_url }}">{{ goods.category }}</a>
                                </td>
                            </tr>
                            <tr>
                                <td>Tags</td>
                                <td>
                                    {% for tag in goods.tags.all %}
                                        <el><a href="{{ tag.get_absolute_url }}">{{ tag }}</a></el>
                                    {% endfor %}
                                </td>
                            </tr>
                            <tr>
                                <td>In stock</td>
                                <td>{{ goods.in_stock }}</td>
                            </tr>
                            <tr>
                                <td>Rating</td>
                                <td>
                                    {{ goods.rating.average_rating }}{% show_rating goods %} {{ goods.rating.rating_counter }}
                                    Votes
                                </td>
                            </tr>
                            <tr>
                                <td>discount</td>
                                <td>{{ goods.discount }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="pull-left"><a style="margin-left: 10px" class="btn btn-default"
                                                  href="{% url 'shop_list' %}">Back to
                            shop</a></div>
                        {% if goods.id not in cart_goods_id %}
                            <form class="" action="{% url 'to_cart' %}"
                                  method="post">{% csrf_token %}
                                <input class="hidden" name="pk" value="{{ goods.id }}">
                                <input style="margin-right: 10px"
                                       class="btn btn-primary {% if not goods.in_stock %}disabled{% endif %} pull-right"
                                       name="submit" type="submit" value="Add to cart"/>
                                <input type="number" style="margin-right: 15px; margin-top: 5px; width: 35px"
                                       class="pull-right" value="1"
                                       step="1" id="count" name="count" min="1" max="99">
                                <label style="margin-top: 7px; margin-right: 10px" class="pull-right"
                                       for="count">Count:</label>
                            </form>
                        {% else %}
                            <a href="{% url 'index_cart' %}" class="btn btn-primary pull-right"
                               style="margin-right: 10px">
                                See in cart
                            </a>

                            <div class="pull-right" style="margin: 6px">You already add this goods in your cart!</div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% if user.is_authenticated and not user.is_staff %}
                {% if is_goods_rated_by_user %}
                    <h4>You are already reviewed this goods</h4>
                    <a class="btn btn-primary" role="button" data-toggle="collapse" href="#collapseForm"
                       aria-expanded="false" aria-controls="collapseForm">Show your review</a>
                {% else %}
                    <h4>Write your review</h4>
                {% endif %}
                <div {% if is_goods_rated_by_user %}class="collapse"{% endif %} id="collapseForm">
                    <form action="{% url 'shop_review' %}" method="post"> {% csrf_token %}
                        <input type="hidden" name="goods_id" value="{{ goods.id }}"/>

                        <div class="form-group">
                            <textarea rows=4 class="form-control" name="review_text">{{ review_text }}</textarea>
                            {% if form.review_text.errors %}
                                <div class="alert alert-danger" role="alert">{{ form.review_text.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="stars">
                            <input class="star star-5" id="star-5" type="radio" value="5" name="rating"/>
                            <label class="star star-5" for="star-5"></label>
                            <input class="star star-4" id="star-4" type="radio" value="4" name="rating"/>
                            <label class="star star-4" for="star-4"></label>
                            <input class="star star-3" id="star-3" type="radio" value="3" name="rating"/>
                            <label class="star star-3" for="star-3"></label>
                            <input class="star star-2" id="star-2" type="radio" value="2" name="rating"/>
                            <label class="star star-2" for="star-2"></label>
                            <input class="star star-1" id="star-1" type="radio" value="1" name="rating"/>
                            <label class="star star-1" for="star-1"></label>
                        </div>
                        {% if is_goods_rated_by_user %}
                            <input class="btn btn-primary pull-right" type="submit" name="add" value="Edit review"/>
                            <input id="review-delete" class="btn btn-danger pull-right" type="submit" name="delete"
                                   value="Delete"/>
                        {% else %}
                            <input class="btn btn-primary pull-right" type="submit" name="add" value="Add review"/>
                        {% endif %}
                    </form>
                </div>
            {% else %}
                {% if not user.is_staff %}
                    <h4>To leave review please <a href="{% url 'login_user' %}">login</a></h4>
                {% endif %}
            {% endif %}
            {% if goods.review_set.all %}
                <h4>Reviews:</h4>
            {% endif %}
            {% for review in goods.review_set.all %}
                <div id="review-{{ review.id }}" class="panel panel-default" data-comment_id="{{ review.id }}">
                    <div class="panel-heading">
                        <div>
                            {% if review.rating > 0 %}
                                {% show_rating goods review.author %}
                            {% endif %}
                            {{ review.author.get_short_name }} published {{ review.published|timesince }} ago
                            {% if user.is_staff %}
                                <div class="pull-right">
                                    <a class='btn btn-danger btn-xs' name="remove" data-id="{{ review.id }}"><span
                                            class="fa fa-times"></span></a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    {% if review.review_text %}
                        <div class="panel-body">
                            <div>
                                <div>
                                    {{ review.review_text }}
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $("[id$=" + {{ rating }} +"]").attr("checked", "checked");
        var ask_confirm = true;
        $("#review-delete").click(function (event) {
            if (ask_confirm) {
                event.preventDefault();
                bootbox.confirm('Are you sure?', function (result) {
                    if (result) {
                        ask_confirm = false;
                        $(event.target).trigger('click');
                    }
                })
            }
        });
        $("[name^=remove]").click(function () {
            var id = $(this).data('id');
            var del_url = "{% url 'shop_review_delete' %}";
            $.post(del_url, {'review_id': id}).done(function (data) {
                if (data.status === 'ok') {
                    var block_id = '#review-' + id;
                    $(block_id).hide();
                    $().toastmessage('showToast', {
                        text: data.message,
                        position: 'top-center',
                        type: 'success'
                    });
                }
            }).fail(function (data) {
                $().toastmessage('showToast', {
                    text: data.message,
                    position: 'top-center',
                    type: 'error'
                });
            })
        });
    </script>
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <style>
        div.stars {
            width: 270px;
            display: inline-block;
            margin-top: -20px;
        }

        input.star {
            display: none;
        }

        label.star {
            float: right;
            padding: 10px;
            font-size: 36px;
            color: #444;
            transition: all .2s;
        }

        input.star:checked ~ label.star:before {
            content: '\f005';
            color: #FD4;
            transition: all .25s;
        }

        input.star-5:checked ~ label.star:before {
            color: #FE7;
            text-shadow: 0 0 20px #952;
        }

        input.star-1:checked ~ label.star:before {
            color: #F62;
        }

        label.star:hover {
            transform: rotate(-15deg) scale(1.3);
        }

        label.star:before {
            content: '\f006';
            font-family: FontAwesome;
        }
    </style>
{% endblock %}

team1_ecommerce/templates/shop/rating_show.html
{% for star in '12345' %}
    <el><span style="color:goldenrod"
              class="glyphicon glyphicon-star{% if forloop.counter > rating %}-empty{% endif %}"
              aria-hidden="true"></span></el>
{% endfor %}